# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/song/dev/cpp/qt/bathysat_post/bathypost.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BathyPost(object):
    def setupUi(self, BathyPost):
        BathyPost.setObjectName("BathyPost")
        BathyPost.resize(400, 327)
        self.centralwidget = QtWidgets.QWidget(BathyPost)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_gpsBrowser = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_gpsBrowser.setObjectName("lineEdit_gpsBrowser")
        self.horizontalLayout.addWidget(self.lineEdit_gpsBrowser)
        self.pushButton_browserGps = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_browserGps.setObjectName("pushButton_browserGps")
        self.horizontalLayout.addWidget(self.pushButton_browserGps)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_sonarBrowser = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_sonarBrowser.setObjectName("lineEdit_sonarBrowser")
        self.horizontalLayout_2.addWidget(self.lineEdit_sonarBrowser)
        self.pushButton_brawserSonar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_brawserSonar.setObjectName("pushButton_brawserSonar")
        self.horizontalLayout_2.addWidget(self.pushButton_brawserSonar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.comboBox_zone = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_zone.setObjectName("comboBox_zone")
        self.comboBox_zone.addItem("")
        self.comboBox_zone.addItem("")
        self.comboBox_zone.addItem("")
        self.comboBox_zone.addItem("")
        self.comboBox_zone.addItem("")
        self.comboBox_zone.addItem("")
        self.comboBox_zone.addItem("")
        self.comboBox_zone.addItem("")
        self.comboBox_zone.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_zone)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.plainTextEdit_gps = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_gps.setReadOnly(True)
        self.plainTextEdit_gps.setObjectName("plainTextEdit_gps")
        self.horizontalLayout_5.addWidget(self.plainTextEdit_gps)
        self.plainTextEdit_bathy = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_bathy.setReadOnly(True)
        self.plainTextEdit_bathy.setObjectName("plainTextEdit_bathy")
        self.horizontalLayout_5.addWidget(self.plainTextEdit_bathy)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.plainTextEdit_result = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_result.setReadOnly(True)
        self.plainTextEdit_result.setObjectName("plainTextEdit_result")
        self.verticalLayout.addWidget(self.plainTextEdit_result)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(93, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_calculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_calculate.setEnabled(False)
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.horizontalLayout_4.addWidget(self.pushButton_calculate)
        spacerItem1 = QtWidgets.QSpacerItem(93, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        BathyPost.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BathyPost)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 19))
        self.menubar.setObjectName("menubar")
        BathyPost.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BathyPost)
        self.statusbar.setObjectName("statusbar")
        BathyPost.setStatusBar(self.statusbar)

        self.retranslateUi(BathyPost)
        QtCore.QMetaObject.connectSlotsByName(BathyPost)

    def retranslateUi(self, BathyPost):
        _translate = QtCore.QCoreApplication.translate
        BathyPost.setWindowTitle(_translate("BathyPost", "MainWindow"))
        self.label.setText(_translate("BathyPost", "GPS"))
        self.pushButton_browserGps.setText(_translate("BathyPost", "Browser"))
        self.label_2.setText(_translate("BathyPost", "Sonar"))
        self.pushButton_brawserSonar.setText(_translate("BathyPost", "Browser"))
        self.label_3.setText(_translate("BathyPost", "Projection"))
        self.comboBox_zone.setCurrentText(_translate("BathyPost", "CC42"))
        self.comboBox_zone.setItemText(0, _translate("BathyPost", "CC42"))
        self.comboBox_zone.setItemText(1, _translate("BathyPost", "CC43"))
        self.comboBox_zone.setItemText(2, _translate("BathyPost", "CC44"))
        self.comboBox_zone.setItemText(3, _translate("BathyPost", "CC45"))
        self.comboBox_zone.setItemText(4, _translate("BathyPost", "CC46"))
        self.comboBox_zone.setItemText(5, _translate("BathyPost", "CC47"))
        self.comboBox_zone.setItemText(6, _translate("BathyPost", "CC48"))
        self.comboBox_zone.setItemText(7, _translate("BathyPost", "CC49"))
        self.comboBox_zone.setItemText(8, _translate("BathyPost", "CC50"))
        self.pushButton_calculate.setText(_translate("BathyPost", "Calculate"))

