# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bathypost.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BathyPost(object):
    def setupUi(self, BathyPost):
        BathyPost.setObjectName("BathyPost")
        BathyPost.resize(400, 327)
        self.centralwidget = QtWidgets.QWidget(BathyPost)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_DataBrowser = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_DataBrowser.setObjectName("lineEdit_DataBrowser")
        self.horizontalLayout.addWidget(self.lineEdit_DataBrowser)
        self.pushButton_Browser = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Browser.setObjectName("pushButton_Browser")
        self.horizontalLayout.addWidget(self.pushButton_Browser)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 1, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.comboBox_CCZone = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_CCZone.setObjectName("comboBox_CCZone")
        self.comboBox_CCZone.addItem("")
        self.comboBox_CCZone.addItem("")
        self.comboBox_CCZone.addItem("")
        self.comboBox_CCZone.addItem("")
        self.comboBox_CCZone.addItem("")
        self.comboBox_CCZone.addItem("")
        self.comboBox_CCZone.addItem("")
        self.comboBox_CCZone.addItem("")
        self.comboBox_CCZone.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_CCZone)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_GpsHeight = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_GpsHeight.setObjectName("lineEdit_GpsHeight")
        self.horizontalLayout_2.addWidget(self.lineEdit_GpsHeight)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(93, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_Calculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Calculate.setEnabled(False)
        self.pushButton_Calculate.setObjectName("pushButton_Calculate")
        self.horizontalLayout_4.addWidget(self.pushButton_Calculate)
        spacerItem1 = QtWidgets.QSpacerItem(93, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 2)
        self.tableView_2 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_2.setObjectName("tableView_2")
        self.gridLayout.addWidget(self.tableView_2, 4, 0, 1, 2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.pushButton_Save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Save.setEnabled(False)
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.horizontalLayout_5.addWidget(self.pushButton_Save)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_5, 5, 0, 1, 2)
        BathyPost.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BathyPost)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 19))
        self.menubar.setObjectName("menubar")
        BathyPost.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BathyPost)
        self.statusbar.setObjectName("statusbar")
        BathyPost.setStatusBar(self.statusbar)

        self.retranslateUi(BathyPost)
        QtCore.QMetaObject.connectSlotsByName(BathyPost)

    def retranslateUi(self, BathyPost):
        _translate = QtCore.QCoreApplication.translate
        BathyPost.setWindowTitle(_translate("BathyPost", "MainWindow"))
        self.label.setText(_translate("BathyPost", "BathySat File"))
        self.pushButton_Browser.setText(_translate("BathyPost", "Browser"))
        self.label_3.setText(_translate("BathyPost", "Projection"))
        self.comboBox_CCZone.setCurrentText(_translate("BathyPost", "CC42"))
        self.comboBox_CCZone.setItemText(0, _translate("BathyPost", "CC42"))
        self.comboBox_CCZone.setItemText(1, _translate("BathyPost", "CC43"))
        self.comboBox_CCZone.setItemText(2, _translate("BathyPost", "CC44"))
        self.comboBox_CCZone.setItemText(3, _translate("BathyPost", "CC45"))
        self.comboBox_CCZone.setItemText(4, _translate("BathyPost", "CC46"))
        self.comboBox_CCZone.setItemText(5, _translate("BathyPost", "CC47"))
        self.comboBox_CCZone.setItemText(6, _translate("BathyPost", "CC48"))
        self.comboBox_CCZone.setItemText(7, _translate("BathyPost", "CC49"))
        self.comboBox_CCZone.setItemText(8, _translate("BathyPost", "CC50"))
        self.label_2.setText(_translate("BathyPost", "GPS Height"))
        self.label_4.setText(_translate("BathyPost", "(m)"))
        self.pushButton_Calculate.setText(_translate("BathyPost", "Calculate"))
        self.pushButton_Save.setText(_translate("BathyPost", "Save"))

