# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 545)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_importBathyData = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_importBathyData.setObjectName("pushButton_importBathyData")
        self.verticalLayout.addWidget(self.pushButton_importBathyData)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.timeEdit_BathyStartTime = QtWidgets.QTimeEdit(self.groupBox_2)
        self.timeEdit_BathyStartTime.setObjectName("timeEdit_BathyStartTime")
        self.horizontalLayout.addWidget(self.timeEdit_BathyStartTime)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.timeEdit_BathyEndTime = QtWidgets.QTimeEdit(self.groupBox_2)
        self.timeEdit_BathyEndTime.setTime(QtCore.QTime(23, 59, 0))
        self.timeEdit_BathyEndTime.setObjectName("timeEdit_BathyEndTime")
        self.horizontalLayout_2.addWidget(self.timeEdit_BathyEndTime)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox_BathyDepth = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_BathyDepth.setChecked(True)
        self.checkBox_BathyDepth.setObjectName("checkBox_BathyDepth")
        self.horizontalLayout_7.addWidget(self.checkBox_BathyDepth)
        self.checkBox_BathyE = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_BathyE.setChecked(True)
        self.checkBox_BathyE.setObjectName("checkBox_BathyE")
        self.horizontalLayout_7.addWidget(self.checkBox_BathyE)
        self.checkBox_BathyW = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_BathyW.setObjectName("checkBox_BathyW")
        self.horizontalLayout_7.addWidget(self.checkBox_BathyW)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_BathyN = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_BathyN.setChecked(True)
        self.checkBox_BathyN.setObjectName("checkBox_BathyN")
        self.horizontalLayout_8.addWidget(self.checkBox_BathyN)
        self.checkBox_BathyS = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_BathyS.setObjectName("checkBox_BathyS")
        self.horizontalLayout_8.addWidget(self.checkBox_BathyS)
        self.checkBox_BathyA = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_BathyA.setObjectName("checkBox_BathyA")
        self.horizontalLayout_8.addWidget(self.checkBox_BathyA)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.plainTextEdit_BathyTerminal = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_BathyTerminal.setDocumentTitle("")
        self.plainTextEdit_BathyTerminal.setObjectName("plainTextEdit_BathyTerminal")
        self.verticalLayout_4.addWidget(self.plainTextEdit_BathyTerminal)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_12.addWidget(self.label_3)
        self.comboBox_BathyReferencePoint = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_BathyReferencePoint.setObjectName("comboBox_BathyReferencePoint")
        self.horizontalLayout_12.addWidget(self.comboBox_BathyReferencePoint)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_importGpsData = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_importGpsData.setObjectName("pushButton_importGpsData")
        self.verticalLayout_2.addWidget(self.pushButton_importGpsData)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.timeEdit_GpsStartTime = QtWidgets.QTimeEdit(self.groupBox)
        self.timeEdit_GpsStartTime.setObjectName("timeEdit_GpsStartTime")
        self.horizontalLayout_5.addWidget(self.timeEdit_GpsStartTime)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.timeEdit_GpsEndTime = QtWidgets.QTimeEdit(self.groupBox)
        self.timeEdit_GpsEndTime.setTime(QtCore.QTime(23, 59, 0))
        self.timeEdit_GpsEndTime.setObjectName("timeEdit_GpsEndTime")
        self.horizontalLayout_6.addWidget(self.timeEdit_GpsEndTime)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBox_GpsW = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_GpsW.setChecked(False)
        self.checkBox_GpsW.setObjectName("checkBox_GpsW")
        self.horizontalLayout_9.addWidget(self.checkBox_GpsW)
        self.checkBox_GpsE = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_GpsE.setChecked(True)
        self.checkBox_GpsE.setObjectName("checkBox_GpsE")
        self.horizontalLayout_9.addWidget(self.checkBox_GpsE)
        self.checkBox_GpsElev = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_GpsElev.setChecked(True)
        self.checkBox_GpsElev.setObjectName("checkBox_GpsElev")
        self.horizontalLayout_9.addWidget(self.checkBox_GpsElev)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkBox_GpsN = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_GpsN.setChecked(True)
        self.checkBox_GpsN.setObjectName("checkBox_GpsN")
        self.horizontalLayout_10.addWidget(self.checkBox_GpsN)
        self.checkBox_GpsS = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_GpsS.setObjectName("checkBox_GpsS")
        self.horizontalLayout_10.addWidget(self.checkBox_GpsS)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.plainTextEdit_GpsTerminal = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_GpsTerminal.setObjectName("plainTextEdit_GpsTerminal")
        self.verticalLayout_3.addWidget(self.plainTextEdit_GpsTerminal)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.comboBox_GpsReferencePoint = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_GpsReferencePoint.setObjectName("comboBox_GpsReferencePoint")
        self.horizontalLayout_4.addWidget(self.comboBox_GpsReferencePoint)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_13.addWidget(self.groupBox)
        self.gridLayout.addLayout(self.horizontalLayout_13, 0, 0, 1, 2)
        self.plainTextEdit_MatchResult = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit_MatchResult.setDocumentTitle("")
        self.plainTextEdit_MatchResult.setObjectName("plainTextEdit_MatchResult")
        self.gridLayout.addWidget(self.plainTextEdit_MatchResult, 1, 0, 1, 2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.lineEdit_Hdiff = QtWidgets.QLineEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Hdiff.sizePolicy().hasHeightForWidth())
        self.lineEdit_Hdiff.setSizePolicy(sizePolicy)
        self.lineEdit_Hdiff.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Hdiff.setObjectName("lineEdit_Hdiff")
        self.horizontalLayout_11.addWidget(self.lineEdit_Hdiff)
        self.gridLayout.addLayout(self.horizontalLayout_11, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.checkBox_Clear = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_Clear.setObjectName("checkBox_Clear")
        self.horizontalLayout_3.addWidget(self.checkBox_Clear)
        self.pushButton_Match = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Match.setObjectName("pushButton_Match")
        self.horizontalLayout_3.addWidget(self.pushButton_Match)
        self.pushButton_Format = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Format.setObjectName("pushButton_Format")
        self.horizontalLayout_3.addWidget(self.pushButton_Format)
        self.pushButton_Export = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_Export.setObjectName("pushButton_Export")
        self.horizontalLayout_3.addWidget(self.pushButton_Export)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 587, 19))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BathySat(GEOSAT)"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Bathy Data"))
        self.pushButton_importBathyData.setText(_translate("MainWindow", "Import Bathy Data"))
        self.label.setText(_translate("MainWindow", "   Start Time:"))
        self.label_6.setText(_translate("MainWindow", "    End Time:"))
        self.checkBox_BathyDepth.setText(_translate("MainWindow", "Depth"))
        self.checkBox_BathyE.setText(_translate("MainWindow", "E"))
        self.checkBox_BathyW.setText(_translate("MainWindow", "W"))
        self.checkBox_BathyN.setText(_translate("MainWindow", "N"))
        self.checkBox_BathyS.setText(_translate("MainWindow", "S"))
        self.checkBox_BathyA.setText(_translate("MainWindow", "A"))
        self.label_3.setText(_translate("MainWindow", "Reference point"))
        self.groupBox.setTitle(_translate("MainWindow", "GPS Data"))
        self.pushButton_importGpsData.setText(_translate("MainWindow", "Import GPS Data"))
        self.label_2.setText(_translate("MainWindow", "   Start Time:"))
        self.label_5.setText(_translate("MainWindow", "    End Time:"))
        self.checkBox_GpsW.setText(_translate("MainWindow", "W"))
        self.checkBox_GpsE.setText(_translate("MainWindow", "E"))
        self.checkBox_GpsElev.setText(_translate("MainWindow", "Elev"))
        self.checkBox_GpsN.setText(_translate("MainWindow", "N"))
        self.checkBox_GpsS.setText(_translate("MainWindow", "S"))
        self.label_4.setText(_translate("MainWindow", "Reference point"))
        self.label_7.setText(_translate("MainWindow", "                      H_diff  :"))
        self.lineEdit_Hdiff.setText(_translate("MainWindow", "0"))
        self.checkBox_Clear.setText(_translate("MainWindow", "Clear"))
        self.pushButton_Match.setText(_translate("MainWindow", "Match"))
        self.pushButton_Format.setText(_translate("MainWindow", "Format"))
        self.pushButton_Export.setText(_translate("MainWindow", "Export"))

