# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow2.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!
from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(517, 276)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.lineEdit_X = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_X.setGeometry(QtCore.QRect(40, 120, 133, 20))
        self.lineEdit_X.setText("")
        self.lineEdit_X.setObjectName("lineEdit_X")
        self.Y = QtWidgets.QLabel(self.centralWidget)
        self.Y.setGeometry(QtCore.QRect(190, 120, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Y.sizePolicy().hasHeightForWidth())
        self.Y.setSizePolicy(sizePolicy)
        self.Y.setLineWidth(1)
        self.Y.setAlignment(QtCore.Qt.AlignCenter)
        self.Y.setObjectName("Y")
        self.lineEdit_Y = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_Y.setGeometry(QtCore.QRect(210, 120, 133, 20))
        self.lineEdit_Y.setObjectName("lineEdit_Y")
        self.lineEdit_Z = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_Z.setGeometry(QtCore.QRect(380, 120, 133, 20))
        self.lineEdit_Z.setObjectName("lineEdit_Z")
        self.coord_base = QtWidgets.QLabel(self.centralWidget)
        self.coord_base.setGeometry(QtCore.QRect(170, 90, 157, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coord_base.sizePolicy().hasHeightForWidth())
        self.coord_base.setSizePolicy(sizePolicy)
        self.coord_base.setLineWidth(1)
        self.coord_base.setAlignment(QtCore.Qt.AlignCenter)
        self.coord_base.setObjectName("coord_base")
        self.Calculer = QtWidgets.QPushButton(self.centralWidget)
        self.Calculer.setGeometry(QtCore.QRect(50, 160, 201, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Calculer.sizePolicy().hasHeightForWidth())
        self.Calculer.setSizePolicy(sizePolicy)
        self.Calculer.setObjectName("Calculer")
        self.X = QtWidgets.QLabel(self.centralWidget)
        self.X.setGeometry(QtCore.QRect(20, 120, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.X.sizePolicy().hasHeightForWidth())
        self.X.setSizePolicy(sizePolicy)
        self.X.setLineWidth(1)
        self.X.setAlignment(QtCore.Qt.AlignCenter)
        self.X.setObjectName("X")
        self.titre = QtWidgets.QLabel(self.centralWidget)
        self.titre.setGeometry(QtCore.QRect(9, 9, 500, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.titre.setFont(font)
        self.titre.setAlignment(QtCore.Qt.AlignCenter)
        self.titre.setObjectName("titre")
        self.Photo = QtWidgets.QLabel(self.centralWidget)
        self.Photo.setGeometry(QtCore.QRect(280, 160, 200, 48))
        self.Photo.setText("")
        self.Photo.setPixmap(QtGui.QPixmap("G:/geosat.gif"))
        self.Photo.setObjectName("Photo")
        self.Parcourir1 = QtWidgets.QPushButton(self.centralWidget)
        self.Parcourir1.setGeometry(QtCore.QRect(260, 50, 131, 21))
        self.Parcourir1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Parcourir1.setObjectName("Parcourir1")
        self.entree = QtWidgets.QLabel(self.centralWidget)
        self.entree.setGeometry(QtCore.QRect(130, 50, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entree.sizePolicy().hasHeightForWidth())
        self.entree.setSizePolicy(sizePolicy)
        self.entree.setAlignment(QtCore.Qt.AlignCenter)
        self.entree.setObjectName("entree")
        self.Z = QtWidgets.QLabel(self.centralWidget)
        self.Z.setGeometry(QtCore.QRect(360, 120, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Z.sizePolicy().hasHeightForWidth())
        self.Z.setSizePolicy(sizePolicy)
        self.Z.setLineWidth(1)
        self.Z.setAlignment(QtCore.Qt.AlignCenter)
        self.Z.setObjectName("Z")
        self.lineEdit_X.raise_()
        self.Y.raise_()
        self.Z.raise_()
        self.lineEdit_Y.raise_()
        self.lineEdit_Z.raise_()
        self.coord_base.raise_()
        self.Calculer.raise_()
        self.X.raise_()
        self.titre.raise_()
        self.Photo.raise_()
        self.Parcourir1.raise_()
        self.Z.raise_()
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 517, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Y.setText(_translate("MainWindow", "Y:"))
        self.coord_base.setText(_translate("MainWindow", "Coordonnées de la base calculée"))
        self.Calculer.setText(_translate("MainWindow", "Calculer"))
        self.X.setText(_translate("MainWindow", "X:"))
        self.titre.setText(_translate("MainWindow", "Programme permettant de transformer un fichier \".rw5\" en un fichier de points colonné"))
        self.Parcourir1.setText(_translate("MainWindow", "Parcourir..."))
        self.entree.setText(_translate("MainWindow", "Fichier en entrée:"))
        self.Z.setText(_translate("MainWindow", "Z:"))


